# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 975bc9fb8aa76bcdf232e1393434807af10618fec242532245975fe1f423c1545860386f43d331a24e739b475cc1ad5a423c9cd0f0c638f39baf64dafbeab0a6

test:
  secret_key_base: 327798f49c8d992049a45d392a7f4b17f201b532faf2843b18fbd98d2aaf29756007ce6c2b02bd4115d9cc89b564f32895192bc3b4f64ab1b1a53887cd74fd38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
